{% set name = "google-cloud-datacatalog" %}
{% set version = "3.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-datacatalog-{{ version }}.tar.gz
  sha256: a841a89bf3596cf05e8adf24734433111ef25585867e17fa4b64d36bce759004

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - google-api-core >=1.22.0,<2.0.0dev
    - grpc-google-iam-v1 >=0.12.3,<0.13dev
    - libcst >=0.2.5
    - proto-plus >=1.4.0
    - python >=3.6

test:
  imports:
    - google.cloud.datacatalog
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-datacatalog
  summary: Google Cloud Data Catalog API API client library
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/googleapis/python-datacatalog
  doc_url: https://cloud.google.com/data-catalog

extra:
  recipe-maintainers:
    - xylar
