{% set name = "google-cloud-datacatalog" %}
{% set version = "3.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-datacatalog-{{ version }}.tar.gz
  sha256: ad1bf9991bdee2a2fee44d19e54790a6eb900652841a5d7a32aa1c468a196f49

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - google-api-core >=1.26.0,<3.0.0dev
    - grpc-google-iam-v1 >=0.12.3,<0.13dev
    - libcst >=0.2.5
    - packaging >=14.3
    - proto-plus >=1.4.0

test:
  imports:
    - google.cloud.datacatalog
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-datacatalog
  summary: Google Cloud Data Catalog API API client library
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/googleapis/python-datacatalog
  doc_url: https://cloud.google.com/data-catalog

extra:
  recipe-maintainers:
    - xylar
